### ISSUE TITLE
Mark all VIPs as finished bug?

### ISSUE THREAD

**Issue by Clueless4ever** [MainVirtualizer/CM3D2Editor#10]
Hello,
I modified my save file using your tool, works great except when I used "Mark all VIPs as finished, not all of them are actually acessible in the "free mode" or "gallery".
http://i.imgur.com/PsUu8dh.png

This is how my free mode VIPs selection looks like after using your tool. It unlocked a lot of the VIPs, but not all of them.
I have all dlcs and I checked that I have them in your tool options.
Here is the modified save file: https://www.dropbox.com/s/g4m87f0ov5j8p1n/SaveData009.save?dl=0

I did some "research" and found out that when I apply this "mark all VIPs..." on new game save(1 new maid), it doesn't unlock any VIP events.

So I do something wrong or is there a bug? Thanks.

**Comment by MainVirtualizer** [comment]
Fixed
