### ISSUE TITLE
希望能增加1.33版本和plus ACT.2扩展包

### ISSUE THREAD

**Issue by paulhuang123321** [MainVirtualizer/CM3D2Editor#11]
plus ACT.2扩展包增加了蛮多东西的
希望大神能增加修改

**Comment by FruitsPunchSamuraiKai** [comment]
哦大神是中国人吗，我也每天十刷新翘首以盼啊...无耻当一次伸手党，大神给个预计更新日期呗(如果会更新的话)

**Comment by MainVirtualizer** [comment]
有哪些扩展包有新技能 这样我就不用一个一个试了

**Comment by FruitsPunchSamuraiKai** [comment]
就只有一个啊，新发售的plus ACT.2，加了4个maid class

**Comment by sonicein** [comment]
新版本修改测试后发现有几个问题，希望大神修正下。
1、全奖杯点击后原版奖杯全亮，但是追加盘act1、2的奖杯全部变暗。
2、全VIP回想中，姐系的对魔忍回想和催眠回想未亮，且无法再从VIP中选择上述四项vip回想。

**Comment by kanonmelodis** [comment]
VIP接待(オフィシャルファンブック)
※母性的なお姉ちゃんは実行不可

姐系本来就不能选催眠和对魔忍的VIP
