### ISSUE TITLE
Yandere, Onee-chan and Bokkuko Personality Traits

### ISSUE THREAD

**Issue by CamperNQQB** [MainVirtualizer/CM3D2Editor#18]
Hey, can you add the personality traits for those 3 peronalities?
http://wiki.anime-sharing.com/hgames/index.php?title=Custom_Maid_3D_2/Gameplay/The_Maid_Profile#H_Traits
Keep up the great work!

**Comment by MainVirtualizer** [comment]
Go to settings and turn these DLCs on.
