### ISSUE TITLE
夜伽DLC10和月度包vip

### ISSUE THREAD

**Issue by sivor0811** [MainVirtualizer/CM3D2Editor#20]
可以的话麻烦大神更新一下支持DLC10和最新的两个月度包的vip
谢谢

**Comment by vtr90086** [comment]
同求 谢谢

**Comment by userkkl** [comment]
还会继续更新吗？

**Comment by innocent0** [comment]
1.46版本不支持了求更新。

**Comment by Gbanb** [comment]
1.46版本不支援了 請求更新。

**Comment by carry0987** [comment]
求大神更新1.48.1

**Comment by MainVirtualizer** [comment]
@carry0987 1.48.1应该没有修改存档的格式吧，忽略警告应该还是可以用的。这个issue我先关了因为其他问题都解决了。如果1.48.1的确不能用的话另外开一个issue吧。

**Comment by carry0987** [comment]
啊，那個，我知道少了什麼...
少瞭解鎖結婚後的三個場景的功能

**Comment by carry0987** [comment]
大大，這個是ACT3的載點：
https://drive.google.com/file/d/0B_qACeIGGKiBUC0wUnFrQ1gyY0U/view?usp=sharing
