### ISSUE TITLE
butt size modifier

### ISSUE THREAD

**Issue by ghost** [MainVirtualizer/CM3D2Editor#25]
the butt size modifier in the "edit body" option isnt changing anything in game.

**Comment by MainVirtualizer** [comment]
Sorry for replying ~2 month later. The modification only changes the data in the save, and it is up to the game to interpret the data. So if you modify it outside defined ranges, the game may or may not respect the value. For some properties, e.g. height, values outside predefined range works, but it may not work for some other properties.
