### ISSUE TITLE
更新

### ISSUE THREAD

**Issue by carry0987** [MainVirtualizer/CM3D2Editor#26]
啊，那個，我知道少了什麼...
1.解鎖結婚後的三個場景 (ACT3,ACT3.1)
2.物品全解鎖新增結婚後的新婚旅行可以購買的土特產 (ACT3,ACT3.1)
3.夜伽DLC V10~12
ACT3 : [下載](https://drive.google.com/file/d/0B_qACeIGGKiBUlljRVRCZ0NpNGM/view?usp=sharing)
ACT3.1 : [下載](https://drive.google.com/file/d/0B_qACeIGGKiBbjMzOXhSRjF4MnM/view?usp=sharing)
夜伽DLC V10 : [下載](https://drive.google.com/file/d/0B_qACeIGGKiBU3JCdmw4a0pQdnM/view?usp=sharing)
夜伽DLC V11 : [下載](https://drive.google.com/file/d/0B_qACeIGGKiBWFdLRkk1VGVuMXc/view?usp=sharing)
夜伽DLC V12 : [下載](https://drive.google.com/file/d/0B_qACeIGGKiBV0ZLVFcyQmxPUGs/view?usp=sharing)

**Comment by carry0987** [comment]
大大要怎麼加入更新包呢？

**Comment by Zazck** [comment]
上面的链接全部失效,麻烦补档

**Comment by carry0987** [comment]
沒問題！我7分鐘後補檔！感謝大大的回覆....我原本以為您已經不更新了

**Comment by carry0987** [comment]
已更新全部的連結！

**Comment by carry0987** [comment]
@Zazck

**Comment by Zazck** [comment]
得晚点才能下完,毕竟人在大陆谷歌盘没速度,邮件提醒也是因为这个原因没第一时间看到,不好意思哈.我还没研究他怎么加的DLC,抽空看看

**Comment by MainVirtualizer** [comment]
夜伽DLC V10~12 早就已经支持了，场景我的确忘记加了，土特产的话我记得送掉了就没了，可以重复购买？这个我不太清楚

**Comment by MainVirtualizer** [comment]
如果你夜伽DLC技能没解锁的话大半是你设置里面没开这个DLC

**Comment by carry0987** [comment]
@MainVirtualizer @Zazck 真的非常感謝兩位前輩的回覆，我沒想到你們在大陸無法使用Github..

**Comment by s557768910** [comment]
甚麼時候會更新新的個性
